default:
  activation:
    number: '37127446401'
    gender: 'Male'
    age: '18 - 24 years'
  code: '123456'
  interests:
    - 'Beauty'
    - 'Gaming'
    - 'Pets'
  updates:
    interests:
      - 'Beauty'
      - 'Gaming'
    gender: 'Female'
    age: '35 - 44 years'
